#!/usr/bin/env bash
# exp_26 step 2: three compile-only builds (B0 donor / B1 vendored GSCALE=0 /
# B2 vendored GSCALE=1) from one immutable snapshot. NO GPU WORK.
set -uo pipefail
SC=$HOME/overnight-scratch/e26
DHK=$SC/dhk
FM=$DHK/distributed-kernels/fused_moe
K0=$HOME/amd-master/auto-gpu-kernel/k0_fused_moe

echo "===INSTALL_VENDORED==="
tr -d '\r' < "$SC/incoming/n2_phase1_gm_mps.cpp" > "$FM/n2_phase1_gm_mps.cpp"
sha256sum "$FM/n2_phase1_gm_mps.cpp"
wc -l "$FM/n2_phase1_gm_mps.cpp" "$K0/solution/hip/n2_phase1_gm.cpp"

echo "===VENDOR_DIFF_VS_DONOR==="
diff -u "$K0/solution/hip/n2_phase1_gm.cpp" "$FM/n2_phase1_gm_mps.cpp" > "$SC/out/vendor.diff"
ins=$(grep -c '^+[^+]' "$SC/out/vendor.diff")
del=$(grep -c '^-[^-]' "$SC/out/vendor.diff")
echo "diffstat: +${ins} -${del}   (deletions MUST be 0)"

echo "===MAKE_TUs==="
rm -rf "$SC/tu"; mkdir -p "$SC/tu/b0" "$SC/tu/b1"
cat > "$SC/tu/banner.txt" <<'EOF'
// ###########################################################################
// SCAFFOLDING ONLY -- exp_26 throwaway translation unit. NOT A SHIPPING SOURCE.
// A verbatim copy of distributed-kernels/fused_moe/k0pf6gm_device_tile_mps.hip
// whose ONLY edit is the phase-1 include at :395, so the vendored M6 body can
// be compiled and disassembled without touching the real kernel (owned by
// another agent tonight). Regenerated by overnight/aug11/tools/e26_build.sh;
// delete freely. The real activation patch is exp_26_p1_sched/activate.md.
// ###########################################################################
EOF
cat "$SC/tu/banner.txt" "$FM/k0pf6gm_device_tile_mps.hip" > "$SC/tu/b0/k0pf6gm_device_tile_mps.hip"
sed 's|^#include "n2_phase1_gm.cpp"$|#include "n2_phase1_gm_mps.cpp"|' \
  "$FM/k0pf6gm_device_tile_mps.hip" \
  | cat "$SC/tu/banner.txt" - > "$SC/tu/b1/k0pf6gm_device_tile_mps.hip"
echo "--- b0 vs b1 must differ on EXACTLY one line ---"
diff "$SC/tu/b0/k0pf6gm_device_tile_mps.hip" "$SC/tu/b1/k0pf6gm_device_tile_mps.hip"
echo "(diff above)"

echo "===BUILD (in subha_k1, CPU-only genco)==="
docker exec subha_k1 bash -lc '
set -uo pipefail
H=/home/subvadla
SC=$H/overnight-scratch/e26
DHK=$SC/dhk
K0=$H/amd-master/auto-gpu-kernel/k0_fused_moe
MR=/usr/local/lib/python3.12/dist-packages/mori/_jit-sources
COMMON=(--genco --offload-arch=gfx950 -std=c++20 -O3
  -DKITTENS_CDNA4 -DHIP_ENABLE_WARP_SYNC_BUILTINS -ffast-math
  -mllvm -amdgpu-mfma-vgpr-form=1 -DK0P6GM_G=3 -DN2GM_G=3
  -Rpass-analysis=kernel-resource-usage
  -I$DHK/include
  -I$DHK/distributed-kernels/fused_moe
  -I$K0/solution/hip/hkp
  -I$K0/prefill_opt/kernels
  -I$K0/solution/hip
  -I$MR -I$MR/include -I$MR/src
  -I$MR/3rdparty/spdlog/include -I$MR/3rdparty/msgpack-c/include)

for v in B0 B1 B2; do
  case $v in
    B0) SRC=$SC/tu/b0/k0pf6gm_device_tile_mps.hip; EXTRA=() ;;
    B1) SRC=$SC/tu/b1/k0pf6gm_device_tile_mps.hip; EXTRA=() ;;
    B2) SRC=$SC/tu/b1/k0pf6gm_device_tile_mps.hip; EXTRA=(-DN2GM_P1_SCHED_GSCALE=1) ;;
  esac
  echo "### building $v"
  t0=$SECONDS
  hipcc "${COMMON[@]}" "${EXTRA[@]}" "$SRC" -o $SC/out/$v.hsaco > $SC/out/$v.log 2>&1
  echo "$v exit=$? secs=$((SECONDS-t0))"
  grep -cE "error:" $SC/out/$v.log | sed "s/^/$v errors=/"
done
' 2>&1 | tail -30

echo "===HASHES==="
sha256sum "$SC/out/"*.hsaco 2>/dev/null || echo "(no hsaco)"
ls -la "$SC/out/"
